project:
  type: manuscript
  output-dir: docs
  post-render:
    - _cleanup.R
  
manuscript:
  article: manuscript.qmd
  code-links:
    - repo
    - text: Web Scraping House Data
      icon: code
      href: webscrape.R
    - text: Data Cleaning using LLM
      icon: code
      href: llm.R

format:
  html: 
    other-links:
      - text: Brunei House Price Data
        icon: database
        href: data/hspbn_2024-12-12.csv  
      - text: BDCB RPPI
        icon: database
        href: data/rppi.csv
      - text: Brunei Spatial Area Data
        icon: database
        href: https://github.com/Bruneiverse/bruneimap/blob/main/datasrc/bn_kpg_level_data.csv
  docx: 
    reference-doc: data-in-brief-article-template.docx
    output-file: jamil2025archives
  elsevier-pdf:
    keep-tex: false    
    output-file: jamil2025archives
    number-sections: false
    journal:
      name: Data in Brief
    header-includes:
      - \usepackage[a4paper, margin=1in]{geometry}

execute:
  # echo: false
  cache: true
  freeze: auto
  warning: false
  code-overflow: wrap

editor_options: 
  chunk_output_type: console
  
bibliography:
  - refs-HJ.bib
csl: data-in-brief.csl

engine: knitr

citation: 
  type: article-journal
  issued: 2025
  container-title: "Manuscript in Submission"
  url: http://haziqj.ml/house-price/papers/jamil2025spatio/
google-scholar: true

