project:
  type: manuscript
  output-dir: docs
  post-render:
    - _cleanup.R
  
manuscript:
  article: manuscript.qmd
  resources:
    - data/rppi.csv
  code-links:
    - repo
    - text: BDCB RPPI
      icon: database
      href: data/rppi.csv

format:
  html: default
  docx: 
    reference-doc: data-in-brief-article-template.docx
    output-file: jamil2025property
  elsevier-pdf:
    keep-tex: false    
    output-file: jamil2025property
    journal:
      name: Data in Brief
    header-includes:
      - \usepackage[a4paper, margin=1in]{geometry}

execute:
  # echo: false
  cache: true
  freeze: auto
  warning: false
  code-overflow: wrap

editor_options: 
  chunk_output_type: console
  
bibliography:
  - refs-HJ.bib
csl: data-in-brief.csl
