project:
  type: manuscript
  output-dir: docs
  
manuscript:
  article: manuscript.qmd
  resources:
    - data/rppi.csv
  code-links:
    - repo
    - text: BDCB RPPI
      icon: database
      href: data/rppi.csv

format:
  html: default
  docx: 
    reference-doc: data-in-brief-article-template.docx
    output-file: jamil2025property
  elsevier-pdf:
    keep-tex: false    
    output-file: jamil2025property
    journal:
      name: Data in Brief

execute:
  echo: false
  cache: false
  freeze: auto
  warning: false

editor_options: 
  chunk_output_type: console
  
bibliography:
  - refs-HJ.bib
csl: data-in-brief.csl
